# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180414_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participation',
            name='beforehand_going',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event_participation',
            name='providing_transportation',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, validators=[events.models.year_check]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, validators=[events.models.year_check]),
        ),
    ]
