# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180415_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_participation',
            old_name='lead_asm',
            new_name='is_lead_asm',
        ),
        migrations.RenameField(
            model_name='event_participation',
            old_name='lead_scout',
            new_name='is_lead_scout',
        ),
        migrations.RenameField(
            model_name='event_participation',
            old_name='providing_transportation',
            new_name='is_providing_transportation',
        ),
        migrations.RenameField(
            model_name='event_participation',
            old_name='two_deep_adult_leader',
            new_name='is_two_deep_adult_leader',
        ),
        migrations.RenameField(
            model_name='event_participation',
            old_name='not_going_reason',
            new_name='reason_not_going',
        ),
        migrations.RemoveField(
            model_name='event_participation',
            name='beforehand_contacted_by_PL',
        ),
        migrations.RemoveField(
            model_name='event_participation',
            name='beforehand_going',
        ),
        migrations.AddField(
            model_name='event_participation',
            name='going',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('MAYBE', 'Maybe'), ('NOTGOING', 'No')], max_length=8),
        ),
    ]
